### ISSUE TITLE
希望支持 序号+新名称 序号+原名称

### ISSUE THREAD

**Issue by hausen1012** [JasonGrass/rename#10]
首先感谢大佬开发好用的工具。

有时候比如下载一系列图片，希望给他们一个固定的名称方便查找，以序号区分。比如ubuntu，希望可以修改为 ubuntu01.png、ubuntu02.png ....和 01ubuntu，02ubuntu这种方式。

**Comment by hausen1012** [comment]
补充一下，如果大佬您用quicker的话可以试试这款动作，我目前用得最多的一个动作。https://getquicker.net/Sharedaction?code=4a8d977c-ae95-4376-39c5-08d7bfff7792

**Comment by JasonGrass** [comment]
这两个加起来，执行两次就可以满足你的需求了 

![image](https://github.com/JasonGrass/rename/assets/10756994/675d1ccd-3656-4c78-9ec4-d7e174c2ef7a)
![image](https://github.com/JasonGrass/rename/assets/10756994/3f163746-1026-49f6-94e4-17176cb91d00)

**Comment by hausen1012** [comment]
有点复杂哈哈

**Comment by hausen1012** [comment]
希望可以增加这项一键的，而不是通过多种组合才能达到目的

**Comment by JasonGrass** [comment]
那功能就永远增加不完了，能用基础功能组合的，就不会再新增了

**Comment by JasonGrass** [comment]
不过可以考虑加一个全新命名的规则，补上你这个需求

**Comment by hausen1012** [comment]
这个可以有哈哈，比如说上面这个需求，还有全部随机字符串命名等

**Comment by JasonGrass** [comment]
新版本已添加
