### ISSUE TITLE
提示信息不准确

### ISSUE THREAD

**Issue by hausen1012** [JasonGrass/rename#11]
当使用 edge 最新版 http 访问时，提示浏览器：当前浏览器尚未支持相关 API，请使用最新版本的 Edge 或 Chrome 浏览器。

其实浏览器时最新版本，只是似乎这个api需要在https下访问

**Comment by JasonGrass** [comment]
这应该是两个独立的问题， http 会自动重定向到 https 的，

下次遇到兼容性提示，可以看下具体的浏览版本。或者使用 F12 打开随便一个网站的控制台，输入 `globalThis.showOpenFilePicker`，看下得到的是什么结果。

![image](https://github.com/JasonGrass/rename/assets/10756994/0990f34c-dbea-4435-8c63-c357f686f4c4)

**Comment by hausen1012** [comment]
我这里说的是自己打包的文件自己运行哈，我没有做自动跳转。在http环境下输入 `globalThis.showOpenFilePicker` 会得到 `undefined` 结果

**Comment by JasonGrass** [comment]
嗦嘎，想起来了，文件读取相关的 API，限制了必须是 HTTPS 的网站才能使用。😥

[Window: showOpenFilePicker() method - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/showOpenFilePicker )

![image](https://github.com/JasonGrass/rename/assets/10756994/0a375cde-330e-4eda-9342-2085b6657cd9)

**Comment by hausen1012** [comment]
对的，是这个问题，所以自己部署用不了也可以能是没配置 https 的问题

**Comment by JasonGrass** [comment]
补充了一个 HTTP 协议不兼容的提示：

https://github.com/JasonGrass/rename/commit/b71e6a77458056f355de3ba40b26e0c62a0870dd

**Comment by hausen1012** [comment]
👍
