### ISSUE TITLE
nas场景中希望支持读取docker容器中的目录，而不是要添加浏览器端设备的目录

### ISSUE THREAD

**Issue by zhguanxian** [JasonGrass/rename#12]
如题，nas场景通过docker部署应用后，无法修改nas中的文件，希望能支持添加容器中的目录

**Comment by Powdered-Delta** [comment]
这个项目是纯前端的实现，设计目的就是修改浏览器端设备的文件（调用浏览器api读写文件名）。想改为更改服务端文件的话纯前端很难实现（至少目前我想不到），理论上必须配合一套带文件管理功能的后端才能实现。
