### ISSUE TITLE
感谢，已star，能否增加个docker镜像，方便更新

### ISSUE THREAD

**Issue by dianso** [JasonGrass/rename#8]
感谢，已star，能否增加个docker镜像，方便更新

**Comment by JasonGrass** [comment]
没太理解，我是部署在 vercel 上，只需要 push 代码就可以了，不用管如何更新，也不需要构建镜像

**Comment by JamesSun-LR** [comment]
你的vercel上已经配置好web前端运行环境，所以只要代码更新就行，  楼主想在任意一个没有前端环境的Linux环境里运行docker run ... 就能启动你这个服务
大部分比较成熟的开源都会提供docker镜像

这个web功能不错，加油！

**Comment by JamesSun-LR** [comment]
@dianso 楼主自己也可以fork一个repo，然后注册vercel，导入这个repo就自动布了一个web服务，白嫖

**Comment by JasonGrass** [comment]
可以搜一下前端 docker 打包如何处理，我对这块不算很熟

[用docker打包一个前端项目 - 国服第一李师师 - 博客园](https://www.cnblogs.com/MDGE/p/17109197.html )
[前端vue+docker打包发布-腾讯云开发者社区-腾讯云](https://cloud.tencent.com/developer/article/2108587 )

**Comment by dianso** [comment]
> 可以搜一下前端 docker 打包如何处理，我对这块不算很熟
> 
> [用docker打包一个前端项目 - 国服第一李师师 - 博客园](https://www.cnblogs.com/MDGE/p/17109197.html) [前端vue+docker打包发布-腾讯云开发者社区-腾讯云](https://cloud.tencent.com/developer/article/2108587)

感谢，我试试吧。

这个是不是可以编译出dist文件夹，放到静态页面就能使用？

**Comment by JasonGrass** [comment]
> > 可以搜一下前端 docker 打包如何处理，我对这块不算很熟
> > [用docker打包一个前端项目 - 国服第一李师师 - 博客园](https://www.cnblogs.com/MDGE/p/17109197.html) [前端vue+docker打包发布-腾讯云开发者社区-腾讯云](https://cloud.tencent.com/developer/article/2108587)
> 
> 感谢，我试试吧。
> 
> 这个是不是可以编译出dist文件夹，放到静态页面就能使用？

是的

**Comment by dianso** [comment]
> > > 可以搜一下前端 docker 打包如何处理，我对这块不算很熟
> > > [用docker打包一个前端项目 - 国服第一李师师 - 博客园](https://www.cnblogs.com/MDGE/p/17109197.html) [前端vue+docker打包发布-腾讯云开发者社区-腾讯云](https://cloud.tencent.com/developer/article/2108587)
> > 
> > 
> > 感谢，我试试吧。
> > 这个是不是可以编译出dist文件夹，放到静态页面就能使用？
> 
> 是的

ok，那我写个脚本定期拉取编译就行

**Comment by dianso** [comment]
> @dianso 楼主自己也可以fork一个repo，然后注册vercel，导入这个repo就自动布了一个web服务，白嫖

好的我试试，感谢
