### ISSUE TITLE
能部署在 cloudflare 的 worker 上吗？

### ISSUE THREAD

**Issue by crazypeace** [JasonGrass/rename#9]
有没有简单的部署指导？
能部署在 cloudflare 的 worker 上吗？

**Comment by JasonGrass** [comment]
我不确定 cloudflare 的 worker 能不能部署静态前端项目，你可以自己搜一下。

## 编译静态站点文件
可以安装 npm 之后，在项目根目录运行如下命令，得到编译之后的静态文件
```
npm i 
npm run build
```

在 dist 目录中会得到输出静态文件，可以部署到任何支持前端静态部署的服务上

**Comment by crazypeace** [comment]
我这么干过, 把项目发布为 github page
然后在 cloudflare 的 worker 里拉 一个比如  xxx.github.io/yyyy 的html内容再显示.
